# explorations/multokenization.yaml
---
# Base hyperparameters
named_static_groups:
  - named_group: "1-1-1_1-1-1"
    dataset_sampling_probs: 
      - [1, 1, 1]
    dataset_sampling_probs_final: 
      - [1, 1, 1]

  - named_group: "1-1_1-1"
    dataset_sampling_probs: 
      - [1, 1]
    dataset_sampling_probs_final: 
      - [1, 1]

  - named_group: "linear"
    dataset_sampling_probs_transition_method: [linear]

  - named_group: "byte_jckj"
    dataset: [byte_ntrex_ja]
    dataset_list: [byte_ntrex_ja byte_ntrex_ko byte_ntrex_zh]
    batch_size: [16]
    max_iters: [6450]

  - named_group: "byte_kckj"
    dataset: [byte_ntrex_ko]
    dataset_list: [byte_ntrex_ja byte_ntrex_ko byte_ntrex_zh]
    batch_size: [16]
    max_iters: [3510]

  - named_group: "byte_cckj"
    dataset: [byte_ntrex_zh]
    dataset_list: [byte_ntrex_ja byte_ntrex_ko byte_ntrex_zh]
    batch_size: [16]
    max_iters: [4230]

  - named_group: "ipa_jckj"
    dataset: [ipa_ntrex_ja]
    dataset_list: [ipa_ntrex_ja ipa_ntrex_ko ipa_ntrex_zh]
    batch_size: [16]
    max_iters: [7890]

  - named_group: "tiktoken_jckj"
    dataset: [tik_ntrex_ja]
    dataset_list: [tik_ntrex_ja tik_ntrex_ko tik_ntrex_zh]

  - named_group: "ipa_cckj"
    dataset: [ipa_ntrex_zh]
    dataset_list: [ipa_ntrex_ja ipa_ntrex_ko ipa_ntrex_zh]
    batch_size: [16]
    max_iters: [7830]

  - named_group: "tiktoken_cckj"
    dataset: [tik_ntrex_zh]
    dataset_list: [tik_ntrex_ja tik_ntrex_ko tik_ntrex_zh]

  - named_group: "ipa_kckj"
    dataset: [ipa_ntrex_ko]
    dataset_list: [ipa_ntrex_ja ipa_ntrex_ko ipa_ntrex_zh]
    batch_size: [16]
    max_iters: [4020]

  - named_group: "tiktoken_kckj"
    dataset: [tik_ntrex_ko]
    dataset_list: [tik_ntrex_ja tik_ntrex_ko tik_ntrex_zh]

  - named_group: "ipa_jkj"
    dataset: [ipa_ntrex_ja]
    dataset_list: [ipa_ntrex_ja ipa_ntrex_ko]
    batch_size: [16]
    max_iters: [5260]

  - named_group: "ipa_kkj"
    dataset: [ipa_ntrex_ko]
    dataset_list: [ipa_ntrex_ja ipa_ntrex_ko]
    batch_size: [16]
    max_iters: [2680]

  - named_group: "tiktoken_jkj"
    dataset: [tik_ntrex_ja]
    dataset_list: [tik_ntrex_ja tik_ntrex_ko]
    batch_size: [16]
    max_iters: [2000]

  - named_group: "tiktoken_kkj"
    dataset: [tik_ntrex_ko]
    dataset_list: [tik_ntrex_ja tik_ntrex_ko]
    batch_size: [16]
    max_iters: [2000]

  - named_group: "byte_jkj"
    dataset: [byte_ntrex_ja]
    dataset_list: [byte_ntrex_ja byte_ntrex_ko]
    batch_size: [16]
    max_iters: [4300]

  - named_group: "byte_kkj"
    dataset: [byte_ntrex_ko]
    dataset_list: [byte_ntrex_ja byte_ntrex_ko]
    batch_size: [16]
    max_iters: [2340]

  - named_group: "ipa_jcj"
    dataset: [ipa_ntrex_ja]
    dataset_list: [ipa_ntrex_ja ipa_ntrex_zh]
    batch_size: [16]
    max_iters: [5260]

  - named_group: "ipa_ccj"
    dataset: [ipa_ntrex_zh]
    dataset_list: [ipa_ntrex_ja ipa_ntrex_zh]
    batch_size: [16]
    max_iters: [5220]

  - named_group: "tiktoken_ccj"
    dataset: [tik_ntrex_zh]
    dataset_list: [tik_ntrex_ja tik_ntrex_zh]
    batch_size: [16]
    max_iters: [2000]

  - named_group: "tiktoken_jcj"
    dataset: [tik_ntrex_ja]
    dataset_list: [tik_ntrex_ja tik_ntrex_zh]
    batch_size: [16]
    max_iters: [2000]

  - named_group: "byte_ccj"
    dataset: [byte_ntrex_zh]
    dataset_list: [byte_ntrex_ja byte_ntrex_zh]
    batch_size: [16]
    max_iters: [2820]

  - named_group: "byte_jcj"
    dataset: [byte_ntrex_ja]
    dataset_list: [byte_ntrex_ja byte_ntrex_zh]
    batch_size: [16]
    max_iters: [4300]

  - named_group: "base_batch_iters"
    batch_size: [16]
    max_iters: [3000]

  - named_group: "one_hot_layer0"
    use_lsv: [true]
    lsv_variant: [one_hot]
    apply_lsv_at_layer_idx: [0]

  - named_group: "one_hot_layer6"
    use_lsv: [true]
    lsv_variant: [one_hot]
    apply_lsv_at_layer_idx: [6]

  - named_group: "ohmg_layer0"
    use_lsv: [true]
    lsv_variant: [ohmg]
    apply_lsv_at_layer_idx: [0]

  - named_group: "ohmg_layer6"
    use_lsv: [true]
    lsv_variant: [ohmg]
    apply_lsv_at_layer_idx: [6]

  - named_group: "without_lsv"
    use_lsv: [false]

training_mode: [multidataset]
dataset_interleaving: [true]
learning_rate: [6e-4]
n_layer: [12]
n_head: [12]
n_embd: [768]
block_size: [1024]
use_rotary_embeddings: [true]
use_abs_pos_embeddings: [false]
use_qk_norm: [true]
use_qk_norm_scale: [true]
use_peri_ln: [true]
use_gradient_checkpoint: [true]
max_sample_tokens: [100]
eval_interval: [100]
sample_each_eval: [true]
compile: [true]
seed: [1, 2, 3, 4, 5]

parameter_groups:
  # - named_group_static: ["tiktoken_kkj", "1-1_1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["tiktoken_jkj", "1-1_1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["ipa_kkj", "1-1_1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["ipa_jkj", "1-1_1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  - named_group_static: ["byte_kkj", "1-1_1-1", "linear"]
    named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  - named_group_static: ["byte_jkj", "1-1_1-1", "linear"]
    named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["ipa_cckj", "1-1-1_1-1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["ipa_jckj", "1-1-1_1-1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["ipa_kckj", "1-1-1_1-1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  - named_group_static: ["byte_cckj", "1-1-1_1-1-1", "linear"]
    named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  - named_group_static: ["byte_jckj", "1-1-1_1-1-1", "linear"]
    named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  - named_group_static: ["byte_kckj", "1-1-1_1-1-1", "linear"]
    named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["tiktoken_cckj", "1-1-1_1-1-1", "linear", "base_batch_iters"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["tiktoken_jckj", "1-1-1_1-1-1", "linear", "base_batch_iters"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["tiktoken_kckj", "1-1-1_1-1-1", "linear", "base_batch_iters"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["tiktoken_ccj", "1-1_1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["tiktoken_jcj", "1-1_1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["ipa_ccj", "1-1_1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["ipa_jcj", "1-1_1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["byte_ccj", "1-1_1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]

  # - named_group_static: ["byte_jcj", "1-1_1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "ohmg_layer0", "without_lsv"]


  # - named_group_static: ["tiktoken_cckj", "1-1-1_1-1-1", "linear", "base_batch_iters"]
  #   named_group_alternates: ["one_hot_layer0", "one_hot_layer6"]

  # - named_group_static: ["tiktoken_kckj", "1-1-1_1-1-1", "linear", "base_batch_iters"]
  #   named_group_alternates: ["one_hot_layer0", "one_hot_layer6"]

  # - named_group_static: ["tiktoken_jckj", "1-1-1_1-1-1", "linear", "base_batch_iters"]
  #   named_group_alternates: ["one_hot_layer0", "one_hot_layer6"]

  # - named_group_static: ["ipa_cckj", "1-1-1_1-1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "one_hot_layer6"]

  # - named_group_static: ["ipa_kckj", "1-1-1_1-1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "one_hot_layer6"]

  # - named_group_static: ["ipa_jckj", "1-1-1_1-1-1", "linear"]
  #   named_group_alternates: ["one_hot_layer0", "one_hot_layer6"]

  
  # - named_group_static: ["ipa_jckj", "1-1-1_1-1-1", "linear", "base_batch_iters"]
  #   named_group_alternates: ["one_hot_layer0", "one_hot_layer6", "ohmg_layer0", "ohmg_layer6", "without_lsv"]

  # - named_group_static: ["byte_jckj", "1-1-1_1-1-1", "linear", "base_batch_iters"]
  #   named_group_alternates: ["one_hot_layer0", "one_hot_layer6", "ohmg_layer0", "ohmg_layer6", "without_lsv"]

  # - named_group_static: ["tiktoken_jckj", "1-1-1_1-1-1", "linear", "base_batch_iters"]
  #   named_group_alternates: ["one_hot_layer0", "one_hot_layer6", "ohmg_layer0", "ohmg_layer6", "without_lsv"]