# explorations/multokenization.yaml
---
# Base hyperparameters
named_static_groups:
  - named_group: "1-10-10_200-1-1"
    dataset_sampling_probs: 
      - [1, 10, 10]
    dataset_sampling_probs_final: 
      - [200, 1, 1]

  - named_group: "1-1-1_1-1-1"
    dataset_sampling_probs: 
      - [1, 1, 1]
    dataset_sampling_probs_final: 
      - [1, 1, 1]

  - named_group: "1-10-10_20-1-1"
    dataset_sampling_probs: 
      - [1, 10, 10]
    dataset_sampling_probs_final: 
      - [20, 1, 1]

  - named_group: "1-10-10_10-1-1"
    dataset_sampling_probs: 
      - [1, 10, 10]
    dataset_sampling_probs_final: 
      - [10, 1, 1]

  - named_group: "linear"
    dataset_sampling_probs_transition_method: [linear]

  - named_group: "tiktoken_en_same"
    dataset: [snac_cven]
    dataset_list: [snac_cven byte_en commonvoice_en]

  - named_group: "one_hot"
    use_lsv: [true]
    lsv_variant: [one_hot]
    apply_lsv_at_layer_idx: [0, 6]
    tensorboard_run_name: ["one_hot"]

  - named_group: "ohmg"
    use_lsv: [true]
    lsv_variant: [ohmg]
    apply_lsv_at_layer_idx: [0, 6]
    tensorboard_run_name: ["ohmg"]

  - named_group: "without_lsv"
    use_lsv: [false]
    tensorboard_run_name: ["without_lsv"]

training_mode: [multidataset]
multidataset_wte: [true]
dataset_interleaving: [false]
batch_size: [16]
learning_rate: [6e-4]
n_layer: [12]
n_head: [12]
n_embd: [768]
block_size: [1024]
use_rotary_embeddings: [true]
use_abs_pos_embeddings: [false]
use_qk_norm: [true]
use_qk_norm_scale: [true]
use_peri_ln: [true]
use_gradient_checkpoint: [true]
max_sample_tokens: [100]
max_iters: [10000]
warmup_iters: [1000]
eval_interval: [1000]
sample_each_eval: [true]
compile: [true]

parameter_groups:
  - named_group_static: ["tiktoken_en_same", "1-10-10_200-1-1", "linear"]
    named_group_alternates: ["one_hot", "ohmg", "without_lsv"]
  
  - named_group_static: ["tiktoken_en_same", "1-10-10_20-1-1", "linear"]
    named_group_alternates: ["one_hot", "ohmg", "without_lsv"]

  - named_group_static: ["tiktoken_en_same", "1-1-1_1-1-1", "linear"]
    named_group_alternates: ["one_hot", "ohmg", "without_lsv"]

  - named_group_static: ["tiktoken_en_same", "1-10-10_10-1-1", "linear"]
    named_group_alternates: ["one_hot", "ohmg", "without_lsv"]

